### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vsoch** [kevensen/kubernetes-xrdp#2]
heyo @kevensen ! I was really happy to find your repo becase I'm interested in trying out guacamole with minkube (and very new to both) and was wondering if you have any kind of documentation, even if only a few lines? I can offer to give a first shot at something for this repository too if it might be helpful, with some guidance. So far what I'm familiar with is finding a yaml configuration file that might define a Pod and Service, and starting it up, like:

```
$ kubectl create -f guacamole.yaml 
$ kubectl describe service guacamole

$ kubecel get services
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
guacamole-service   ClusterIP      10.106.211.170   <none>        8080/TCP         11h
jupyter             LoadBalancer   10.99.45.42      <pending>     80:30112/TCP     15h
kubernetes          ClusterIP      10.96.0.1        <none>        443/TCP          6d
```
Then when I try to start it, I'm guessing I forgot to set something up (a database? or exposed port?)

```
minikube service guacamole-service
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
```
And then of course `minikube service guacamole` which (I think) would open up to the right port, but it's not started / working yet. I also might have tried to expose something, although I don't think this is right:

```
kubectl expose deployment guacamole --type=LoadBalancer
```
I think I figured out that the ReplicationController needs to be started (I think that is a kind of wrapper for a replicated Pod?)

```
$ kubectl describe rc guacamole-controller
Name:         guacamole-controller
Namespace:    default
Selector:     app=guacamole
Labels:       app=guacamole
Annotations:  <none>
Replicas:     1 current / 1 desired
Pods Status:  0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=guacamole
  Containers:
   guacamole:
    Image:  docker.io/glyptodon/guacamole
    Port:   8080/TCP
    Environment:
      MYSQL_USER:      guacamole_user
      MYSQL_PASSWORD:  guacamole_pass
      MYSQL_DATABASE:  guacamole_db
      MYSQL_HOSTNAME:  blah
    Mounts:            <none>
  Volumes:             <none>
Events:                <none>
```
Note pod status says 1 in waiting! Could you help me get these steps just right? I also noticed that this is a ReplicationController, and do we want to use ReplicationSets? Thank you!

**Comment by vsoch** [comment]
Trying more things! I uncommented `NodePort` and then did `kubectl apply -f guacamole.yml` and then it looks like I have more information, about FailedScheduling?:

```
$ kubectl describe pod guacamole
Name:           guacamole-controller-5tpv9
Namespace:      default
Node:           <none>
Labels:         app=guacamole
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicationController/guacamole-controller
Containers:
  guacamole:
    Image:  docker.io/glyptodon/guacamole
    Port:   8080/TCP
    Environment:
      MYSQL_USER:      guacamole_user
      MYSQL_PASSWORD:  guacamole_pass
      MYSQL_DATABASE:  guacamole_db
      MYSQL_HOSTNAME:  blah
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-h47lj (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  default-token-h47lj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-h47lj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  role=frontend
Tolerations:     <none>
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  7s (x2429 over 11h)  default-scheduler  0/1 nodes are available: 1 MatchNodeSelector.
```

**Comment by kevensen** [comment]
Hi @vsoch.  I believe the "FailedScheduling" is due to the node labels, or lack thereof.  Some components require a node to be labeled as "role=frontend" and others as "role=backend".   In your case, I would recommend removing the "NodeSelector" from the replication controller definitions.

As far as the ReplicationController vs. ReplicaSet, I hadn't noticed that ReplicaSet is a new thing.  I'll look into it.  For the moment, I think ReplicationController is sufficient.

FWIW, I know you are trying minikube, but you may wish to take a look at https://github.com/kevensen/openshift-kiosk as well.  This is an improvement over repo.  You do not need OpenShift.

**Comment by vsoch** [comment]
ahh ok so I removed everything and restarted removing the `NodeSelector` and we are closer! Now there is something about starting the container:

```
Events:
  Type     Reason                 Age                From               Message
  ----     ------                 ----               ----               -------
  Normal   Scheduled              5m                 default-scheduler  Successfully assigned guacamole-controller-xtq5b to minikube
  Normal   SuccessfulMountVolume  5m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-h47lj"
  Normal   Pulling                4m (x4 over 5m)    kubelet, minikube  pulling image "docker.io/glyptodon/guacamole"
  Normal   Pulled                 4m (x4 over 4m)    kubelet, minikube  Successfully pulled image "docker.io/glyptodon/guacamole"
  Normal   Created                4m (x4 over 4m)    kubelet, minikube  Created container
  Normal   Started                4m (x4 over 4m)    kubelet, minikube  Started container
  Warning  BackOff                47s (x20 over 4m)  kubelet, minikube  Back-off restarting failed container
```
Do the other dependencies in this folder (the `guacd` and various ssh tools) need to be started as well?

**Comment by kevensen** [comment]
IIRC you need to start a mysql container first, then the guacd, then guacamole.  The XRDP controller can be started either before or after the rest of guacamole.  But you'll need to start the XRDP before configuring guacamole.

**Comment by vsoch** [comment]
ok thanks!

**Comment by kevensen** [comment]
NP.  Lemme know if you run into other problems.  (sorry, it's been a while since I worked on this particular project)

**Comment by vsoch** [comment]
That's actually meaningful in and of itself - we are deploying a kubernetes cluster (I'm testing with minikube) and some of the admins want to use Guacamole for virtual desktop. My thinking is that it would be best to stay away from this kind of setup (a virtual desktop is not super reproducible) and use things like jupyter notebook, rstudio, but there are likely applications that need graphics that would warrant one. Do you think Guacamole is one of the top contenders for this task (if not, what would you suggest) and then my second question is why did you abandon this project (for a different strategy /solution)?

**Comment by kevensen** [comment]
Guacamole for a VDI has its uses.  Not all applications have a native web interface and require Gnome or KDE (you pointed this out).  I think Guacamole is definitely a contender.  I abandoned this project in favor of https://github.com/kevensen/openshift-kiosk.  

I actually wanted install software, e.g. Eclipse IDE or Firefox, in a container image.  To an extent, this is reproducible.  The container image is immutable and would enforce a baseline of tools for an environment.  From an admin's perspective, this is fantastic.  Persistent data, like a user's home directory, could be saved to a network share via a Kubernetes PV/PVC.  The tools would remain in a fairly stable state.

That said, a VDI environment is no picnic to maintain, whether it's Citrix or Guacamole, etc..  As the Cloud becomes more prevalent, more and more tools are enabling a web-based interface.  SaaS (software-as-a-service) is becoming the norm.  For example, Office 365.

I wouldn't discount Guacamole but I think one must look at what they are trying to achieve in order to determine the best tooling.

Sorry for the rambling...

**Comment by vsoch** [comment]
No this is so very helpful! I was ruminating about this last evening, and my mind came to some of the same thoughts about how this was too much, or at least didn't fit the general spirit of something like kubernetes. Thanks very much for your rambling! I'll close the issue because you have well addressed my questions.
